# -----------------------------
# HTTP SERVER (Port 80)
# -----------------------------
server {
    listen 80;
    server_name programmingprophet.site www.programmingprophet.site;

    location /.well-known/acme-challenge/ {
        alias /var/www/certbot/.well-known/acme-challenge/;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}


# -----------------------------
# HTTPS SERVER (Port 443)
# -----------------------------
server {
    listen 443 ssl;
    server_name programmingprophet.site www.programmingprophet.site;

    ssl_certificate /etc/letsencrypt/live/programmingprophet.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/programmingprophet.site/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }
}
